[package]
name = "mitex"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["OrangeX4"]
license = "MIT"
description = "Convert LaTeX equation to Typst equation."

homepage = "https://github.com/OrangeX4/typst-mitex"
repository = "https://github.com/OrangeX4/typst-mitex"
keywords = ["wasm", "rust", "LaTeX", "equation"]
exclude = ["examples"]